package com.online.market.model;

// Generated 2014-3-30 13:25:23 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * AdminMsg generated by hbm2java
 */
public class AdminMsg implements java.io.Serializable {
	private static final long serialVersionUID = -8653588072823921639L;
	private String adId;
	private User user;
	private Admin admin;
	private String adMsg;
	private Date adTime;
	private Boolean adIsNew;

	public AdminMsg() {
	}

	public AdminMsg(String adId) {
		this.adId = adId;
	}

	public AdminMsg(String adId, User user, Admin admin, String adMsg,
			Date adTime, Boolean adIsNew) {
		this.adId = adId;
		this.user = user;
		this.admin = admin;
		this.adMsg = adMsg;
		this.adTime = adTime;
		this.adIsNew = adIsNew;
	}

	public String getAdId() {
		return this.adId;
	}

	public void setAdId(String adId) {
		this.adId = adId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getAdMsg() {
		return this.adMsg;
	}

	public void setAdMsg(String adMsg) {
		this.adMsg = adMsg;
	}

	public Date getAdTime() {
		return this.adTime;
	}

	public void setAdTime(Date adTime) {
		this.adTime = adTime;
	}

	public Boolean getAdIsNew() {
		return this.adIsNew;
	}

	public void setAdIsNew(Boolean adIsNew) {
		this.adIsNew = adIsNew;
	}

}
