package com.online.market.model;

// Generated 2014-3-30 13:25:23 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private static final long serialVersionUID = -3195752788549840836L;
	private String id;
	private String name;
	private String password;
	private Boolean valid;
	private String role;
	private Set<AdminMsg> adminMsgs = new HashSet<AdminMsg>(0);
	private Set<BackMsg> backMsgs = new HashSet<BackMsg>(0);
	private Set<PwdMsg> pwdMsgs = new HashSet<PwdMsg>(0);

	public Admin() {
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getValid() {
		return valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set<AdminMsg> getAdminMsgs() {
		return adminMsgs;
	}

	public void setAdminMsgs(Set<AdminMsg> adminMsgs) {
		this.adminMsgs = adminMsgs;
	}

	public Set<BackMsg> getBackMsgs() {
		return backMsgs;
	}

	public void setBackMsgs(Set<BackMsg> backMsgs) {
		this.backMsgs = backMsgs;
	}

	public Set<PwdMsg> getPwdMsgs() {
		return pwdMsgs;
	}

	public void setPwdMsgs(Set<PwdMsg> pwdMsgs) {
		this.pwdMsgs = pwdMsgs;
	}

	public Admin(String id, String name, String password, Boolean valid,
			String role, Set<AdminMsg> adminMsgs, Set<BackMsg> backMsgs,
			Set<PwdMsg> pwdMsgs) {
		super();
		this.id = id;
		this.name = name;
		this.password = password;
		this.valid = valid;
		this.role = role;
		this.adminMsgs = adminMsgs;
		this.backMsgs = backMsgs;
		this.pwdMsgs = pwdMsgs;
	}


}
