package com.online.market.model;

// Generated 2014-3-30 13:25:23 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * BackMsg generated by hbm2java
 */
public class BackMsg implements java.io.Serializable {

	private static final long serialVersionUID = 8305577942078616047L;
	private String bid;
	private User user;
	private Admin admin;
	private String bmsg;
	private Date btime;
	private Boolean bisNew;

	public BackMsg() {
	}

	public String getBid() {
		return bid;
	}

	public void setBid(String bid) {
		this.bid = bid;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Admin getAdmin() {
		return admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getBmsg() {
		return bmsg;
	}

	public void setBmsg(String bmsg) {
		this.bmsg = bmsg;
	}

	public Date getBtime() {
		return btime;
	}

	public void setBtime(Date btime) {
		this.btime = btime;
	}

	public Boolean getBisNew() {
		return bisNew;
	}

	public void setBisNew(Boolean bisNew) {
		this.bisNew = bisNew;
	}

	public BackMsg(String bid, User user, Admin admin, String bmsg, Date btime,
			Boolean bisNew) {
		super();
		this.bid = bid;
		this.user = user;
		this.admin = admin;
		this.bmsg = bmsg;
		this.btime = btime;
		this.bisNew = bisNew;
	}

	
}
