package com.online.market.model;

// Generated 2014-3-30 13:25:23 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GComment generated by hbm2java
 */
public class GComment implements java.io.Serializable {

	private static final long serialVersionUID = -9013370444421591452L;
	private String gcId;
	private Goods goods;
	private String gcMsg;
	private Date gcTime;
	private Boolean gcIsNew;
	private String uid;

	public GComment() {
	}

	public GComment(String gcId) {
		this.gcId = gcId;
	}

	
	public String getGcId() {
		return this.gcId;
	}

	public void setGcId(String gcId) {
		this.gcId = gcId;
	}

	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public String getGcMsg() {
		return this.gcMsg;
	}

	public void setGcMsg(String gcMsg) {
		this.gcMsg = gcMsg;
	}

	public Date getGcTime() {
		return this.gcTime;
	}

	public void setGcTime(Date gcTime) {
		this.gcTime = gcTime;
	}

	public Boolean getGcIsNew() {
		return this.gcIsNew;
	}

	public void setGcIsNew(Boolean gcIsNew) {
		this.gcIsNew = gcIsNew;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public GComment(String gcId, Goods goods, String gcMsg, Date gcTime,
			Boolean gcIsNew, String uid) {
		super();
		this.gcId = gcId;
		this.goods = goods;
		this.gcMsg = gcMsg;
		this.gcTime = gcTime;
		this.gcIsNew = gcIsNew;
		this.uid = uid;
	}


}
