package com.online.market.model;

// Generated 2014-3-30 13:25:23 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	private static final long serialVersionUID = 1436618981758777973L;
	private String lid;
	private String lip;
	private String lcontent;
	private Date ltime;
	private String lurl;

	public Log() {
	}

	public Log(String lid, String lip, String lcontent, Date ltime, String lurl) {
		super();
		this.lid = lid;
		this.lip = lip;
		this.lcontent = lcontent;
		this.ltime = ltime;
		this.lurl = lurl;
	}

	public String getLid() {
		return lid;
	}

	public void setLid(String lid) {
		this.lid = lid;
	}

	public String getLip() {
		return lip;
	}

	public void setLip(String lip) {
		this.lip = lip;
	}

	public String getLcontent() {
		return lcontent;
	}

	public void setLcontent(String lcontent) {
		this.lcontent = lcontent;
	}

	public Date getLtime() {
		return ltime;
	}

	public void setLtime(Date ltime) {
		this.ltime = ltime;
	}

	public String getLurl() {
		return lurl;
	}

	public void setLurl(String lurl) {
		this.lurl = lurl;
	}

	
}
