package com.online.market.model;

// Generated 2014-3-30 13:25:23 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

//import com.sun.org.apache.xerces.internal.impl.dv.dtd.NMTOKENDatatypeValidator;

/**
 * Needs generated by hbm2java
 */
public class Needs implements java.io.Serializable {

	private static final long serialVersionUID = -4665995063103585851L;
	private String nid;
	private User user;
	private String nname;
	private String ncategory;
	private String ndegree;
	private String nphone;
	private Double nlessPrice;
	private Double nhighesPricet;
	private String nplace;
	private String ndescription;
	private Integer ncollectNum;
	private Integer ncommentNum;
	private Date ntime;
	private Date nendTime;
	private Boolean nvalid;
	private Set<NComment> ncomments = new HashSet<NComment>(0);

	public Needs() {
	}

	public Needs(String nid, User user, String nname, String ncategory, String ndegree, String nphone,
			Double nlessPrice, Double nhighesPricet, String nplace,
			String ndescription, Integer ncollectNum, Integer ncommentNum, Date ntime, Date nendTime, Boolean nvalid,
			Set<NComment> ncomments) {
		super();
		this.nid = nid;
		this.user = user;
		this.nname = nname;
		this.ncategory = ncategory;
		this.ndegree = ndegree;
		this.setNphone(nphone);
		this.nlessPrice = nlessPrice;
		this.nhighesPricet = nhighesPricet;
		this.nplace = nplace;
		this.ndescription = ndescription;
		this.ncollectNum = ncollectNum;
		this.ncommentNum = ncommentNum;
		this.ntime = ntime;
		this.nendTime = nendTime;
		this.nvalid = nvalid;
		this.ncomments = ncomments;
	}

	public String getNid() {
		return nid;
	}

	public void setNid(String nid) {
		this.nid = nid;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getNname() {
		return nname;
	}

	public void setNname(String nname) {
		this.nname = nname;
	}

	public String getNcategory() {
		return ncategory;
	}

	public void setNcategory(String ncategory) {
		this.ncategory = ncategory;
	}

	public String getNdegree() {
		return ndegree;
	}

	public void setNdegree(String ndegree) {
		this.ndegree = ndegree;
	}

	public String getNphone() {
		return nphone;
	}

	public void setNphone(String nphone) {
		this.nphone = nphone;
	}

	public Double getNlessPrice() {
		return nlessPrice;
	}

	public void setNlessPrice(Double nlessPrice) {
		this.nlessPrice = nlessPrice;
	}

	public Double getNhighesPricet() {
		return nhighesPricet;
	}

	public void setNhighesPricet(Double nhighesPricet) {
		this.nhighesPricet = nhighesPricet;
	}

	public String getNplace() {
		return nplace;
	}

	public void setNplace(String nplace) {
		this.nplace = nplace;
	}

	public String getNdescription() {
		return ndescription;
	}

	public void setNdescription(String ndescription) {
		this.ndescription = ndescription;
	}

	public Integer getNcollectNum() {
		return ncollectNum;
	}

	public void setNcollectNum(Integer ncollectNum) {
		this.ncollectNum = ncollectNum;
	}

	public Integer getNcommentNum() {
		return ncommentNum;
	}

	public void setNcommentNum(Integer ncommentNum) {
		this.ncommentNum = ncommentNum;
	}

	public Date getNtime() {
		return ntime;
	}

	public void setNtime(Date ntime) {
		this.ntime = ntime;
	}

	public Date getNendTime() {
		return nendTime;
	}

	public void setNendTime(Date nendTime) {
		this.nendTime = nendTime;
	}

	public Boolean getNvalid() {
		return nvalid;
	}

	public void setNvalid(Boolean nvalid) {
		this.nvalid = nvalid;
	}

	public Set<NComment> getNcomments() {
		return ncomments;
	}

	public void setNcomments(Set<NComment> ncomments) {
		this.ncomments = ncomments;
	}

	
}
