package com.online.market.model;

// Generated 2014-3-30 13:25:23 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * UserMsg generated by hbm2java
 */
public class UserMsg implements java.io.Serializable {

	private String umId;
	private User user;
	private String sendId;
	private String umMsg;
	private Date umTime;
	private Boolean umIsNew;

	public UserMsg() {
	}

	public UserMsg(String umId) {
		this.umId = umId;
	}

	public UserMsg(String umId, User user, String sendId, String umMsg,
			Date umTime, Boolean umIsNew) {
		this.umId = umId;
		this.user = user;
		this.sendId = sendId;
		this.umMsg = umMsg;
		this.umTime = umTime;
		this.umIsNew = umIsNew;
	}

	public String getUmId() {
		return this.umId;
	}

	public void setUmId(String umId) {
		this.umId = umId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSendId() {
		return this.sendId;
	}

	public void setSendId(String sendId) {
		this.sendId = sendId;
	}

	public String getUmMsg() {
		return this.umMsg;
	}

	public void setUmMsg(String umMsg) {
		this.umMsg = umMsg;
	}

	public Date getUmTime() {
		return this.umTime;
	}

	public void setUmTime(Date umTime) {
		this.umTime = umTime;
	}

	public Boolean getUmIsNew() {
		return this.umIsNew;
	}

	public void setUmIsNew(Boolean umIsNew) {
		this.umIsNew = umIsNew;
	}

}
