package com.online.market.model;

// Generated 2014-3-30 13:25:23 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 4034229220029303154L;
	private String uid;
	private int ultUid;
	private String uname;
	private String upwd;
	private String usex;
	private String uphone;
	private String uemail;
	private Date utime;
	private Boolean uvalid;
	private String ugids;
	private Set<Goods> goodses = new HashSet<Goods>(0);
	private Set<UserMsg> userMsgs = new HashSet<UserMsg>(0);
	private Set<Needs> needses = new HashSet<Needs>(0);
	private Set<AdminMsg> adminMsgs = new HashSet<AdminMsg>(0);
	private Set<BackMsg> backMsgs = new HashSet<BackMsg>(0);

	public User() {
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public int getUltUid() {
		return ultUid;
	}

	public void setUltUid(int ultUid) {
		this.ultUid = ultUid;
	}

	public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public String getUsex() {
		return usex;
	}

	public void setUsex(String usex) {
		this.usex = usex;
	}

	public String getUphone() {
		return uphone;
	}

	public void setUphone(String uphone) {
		this.uphone = uphone;
	}

	public String getUemail() {
		return uemail;
	}

	public void setUemail(String uemail) {
		this.uemail = uemail;
	}

	public Date getUtime() {
		return utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public Boolean getUvalid() {
		return uvalid;
	}

	public void setUvalid(Boolean uvalid) {
		this.uvalid = uvalid;
	}

	public String getUgids() {
		return ugids;
	}

	public void setUgids(String ugids) {
		this.ugids = ugids;
	}

	public Set<Goods> getGoodses() {
		return goodses;
	}

	public void setGoodses(Set<Goods> goodses) {
		this.goodses = goodses;
	}

	public Set<UserMsg> getUserMsgs() {
		return userMsgs;
	}

	public void setUserMsgs(Set<UserMsg> userMsgs) {
		this.userMsgs = userMsgs;
	}

	public Set<Needs> getNeedses() {
		return needses;
	}

	public void setNeedses(Set<Needs> needses) {
		this.needses = needses;
	}

	public Set<AdminMsg> getAdminMsgs() {
		return adminMsgs;
	}

	public void setAdminMsgs(Set<AdminMsg> adminMsgs) {
		this.adminMsgs = adminMsgs;
	}

	public Set<BackMsg> getBackMsgs() {
		return backMsgs;
	}

	public void setBackMsgs(Set<BackMsg> backMsgs) {
		this.backMsgs = backMsgs;
	}

	public User(String uid, int ultUid, String uname, String upwd, String usex,
			String uphone, String uemail, Date utime, Boolean uvalid,
			String ugids, Set<Goods> goodses, Set<UserMsg> userMsgs,
			Set<Needs> needses, Set<AdminMsg> adminMsgs, Set<BackMsg> backMsgs) {
		super();
		this.uid = uid;
		this.ultUid = ultUid;
		this.uname = uname;
		this.upwd = upwd;
		this.usex = usex;
		this.uphone = uphone;
		this.uemail = uemail;
		this.utime = utime;
		this.uvalid = uvalid;
		this.ugids = ugids;
		this.goodses = goodses;
		this.userMsgs = userMsgs;
		this.needses = needses;
		this.adminMsgs = adminMsgs;
		this.backMsgs = backMsgs;
	}
	
}
